site_name: {{ cookiecutter.project_name }}
site_description: Documentation for {{ cookiecutter.description }}


site_url: https://github.com/{{ cookiecutter.github_org }}/{{ cookiecutter.project_slug }}
repo_url: https://github.com/{{ cookiecutter.github_org }}/{{ cookiecutter.project_slug }}
repo_name: {{ cookiecutter.github_org }}/{{ cookiecutter.project_slug }}

docs_dir: docs

theme:
  name: materialx
  logo: assets/logo.svg
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - monorepo
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
  - mermaid2
  - glightbox

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.snippets:
      base_path:
        - docs
        - .
  - pymdownx.inlinehilite
  #- pymdownx.tabbed:
  #    alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

  - mkdocs_graphviz:
      priority: 96

extra_javascript:
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js
  # This allows Mermaid to render correctly in the browser
  - https://unpkg.com/mermaid/dist/mermaid.min.js

nav:
  - Overview: index.md
  - Architecture: architecture.md
  - Workflow {{ cookiecutter.task_type }}: workflow.md
  - Makefile targets: makefile-targets.md
  - Troubleshooting: troubleshooting.md
{%- if cookiecutter.include_tools == 'y' %}
  - Tools:
      - {{ cookiecutter.tool_name }}: '!include ./src/{{ cookiecutter.tool_name }}/mkdocs.yml'
{%- endif %}

